driver = webdriver.Chrome()
driver.get("https://testtalents.com")
signUpBtn = driver.find_element(by=By.CLASS, value="tp-btn_dark tp-text-s-semi-bold tp-w-full sm:tp-w-auto")
signUpBtn.click()
fullName = driver.find_element(by=By.ID, value="recruiterRegisterFullName")
Email = driver.find_element(by=By.ID, value="rrecruiterRegisterEmail")
Pass = driver.find_element(by=By.ID, value="recruiterRegisterPassword")
confirmPass = driver.find_element(by=By.ID, value="recruiterRegisterConfirmPassword")
driver.implicitly_wait(0.5)
fullName.send_keys("Test User")
Email.send_keys("anikatahsinraisa20@gmail.com")
Pass.send_keys("Testuser!123")
confirmPass.send_keys("Testuser!123")
signUpbtn1 = driver.find_element(by=By.ID, value="recruiterRegisterFormButton")
signUpbtn1.click()
driver.implicitly_wait(3)
title = driver.title
driver.close()

driver.get("https://testtalents.com")
signUpBtn = driver.find_element(by=By.CLASS, value="text-hind no-underline text-sm-bold color-primary-700")
signUpBtn.click()
driver.implicitly_wait(1)
loginBtn = driver.find_element(by=By.CLASS, value="tp-btn_dark tp-text-s-semi-bold tp-w-full sm:tp-w-auto")
loginBtn.click()
driver.implicitly_wait(1)
Email1 = driver.find_element(by=By.ID, value="recruiterLoginEmail")
Pass1 = driver.find_element(by=By.ID, value="recruiterLoginPassword")
driver.implicitly_wait(1)
Email1.send_keys("anikatahsinraisa20@gmail.com")
Pass1.send_keys("Testuser!123")
loginbtn1 = driver.find_element(by=By.ID, value="recruiterLoginFormButton")
loginbtn1.click()
driver.implicitly_wait(3)
title1 = driver.title
driver.close()

Assert.assertEquals(title,title1)
